user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {

    upstream tomcat_cluster {
        server 192.168.10.11:8080;
        server 192.168.10.12:8080;
        server 192.168.10.13:8080;
    }

    server {
        listen 80;

        server_name localhost;

        # 动态请求（JSP）→ Tomcat集群
        location ~ \.jsp$ {
            proxy_pass http://tomcat_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 静态资源 → Nginx本地
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
